import Foundation

/// Decoded `KokoroRuntimeManifest.json` generated by `build_sdk_bundle.mjs`.
struct KokoroRuntimeManifest: Decodable, Sendable {
    /// Manifest schema version.
    let schemaVersion: Int

    /// SDK commit that generated the bundle.
    let sdkCommit: String

    /// Hugging Face repo ID used for model and voice artifacts.
    let hfRepoID: String

    /// Hugging Face revision used for model and voice artifacts.
    let hfRevision: String

    /// Whether the bundle builder verified local model and voice files against
    /// a Hugging Face download manifest before packaging them.
    let hfProvenanceVerified: Bool?

    /// Minimum supported platform versions declared by the bundle builder.
    let minimumPlatforms: [String: String]?

    /// Human-language tags supported by this generated bundle.
    let supportedLanguages: [String]?

    /// Bundle profile name.
    let bundleProfile: String

    /// Supported bucket seconds.
    let buckets: [Int]

    /// Supported duration token sizes.
    let durationTokenSizes: [Int]

    /// Model package digest entries.
    let modelPackages: [ModelPackage]

    /// Voice file digest entries.
    let voices: [FileDigest]

    /// Runtime asset digest entries.
    let runtimeAssets: RuntimeAssets

    /// JSON coding keys for snake_case manifest fields.
    private enum CodingKeys: String, CodingKey {
        case schemaVersion = "schema_version"
        case sdkCommit = "sdk_commit"
        case hfRepoID = "hf_repo_id"
        case hfRevision = "hf_revision"
        case hfProvenanceVerified = "hf_provenance_verified"
        case minimumPlatforms = "minimum_platforms"
        case supportedLanguages = "supported_languages"
        case bundleProfile = "bundle_profile"
        case buckets
        case durationTokenSizes = "duration_token_sizes"
        case modelPackages = "model_packages"
        case voices
        case runtimeAssets = "runtime_assets"
    }

    /// One file digest entry.
    struct FileDigest: Decodable, Sendable {
        /// Bundle-relative file path.
        let path: String

        /// File byte count.
        let bytes: Int

        /// File SHA-256 digest.
        let sha256: String
    }

    /// One model package digest entry.
    struct ModelPackage: Decodable, Sendable {
        /// Bundle-relative package path.
        let path: String

        /// Stable package tree digest.
        let treeSHA256: String

        /// Number of regular files in the package.
        let fileCount: Int

        /// Total package bytes.
        let bytes: Int

        /// Regular files included in this package.
        let files: [FileDigest]

        /// JSON coding keys for snake_case package fields.
        private enum CodingKeys: String, CodingKey {
            case path
            case treeSHA256 = "tree_sha256"
            case fileCount = "file_count"
            case bytes
            case files
        }
    }

    /// Runtime asset digest entries.
    struct RuntimeAssets: Decodable, Sendable {
        /// Kokoro vocab file digest.
        let vocab: FileDigest

        /// hn-NSF weights file digest.
        let hnsfWeights: FileDigest

        /// JSON coding keys for snake_case runtime asset fields.
        private enum CodingKeys: String, CodingKey {
            case vocab
            case hnsfWeights = "hnsf_weights"
        }
    }
}
