#!/usr/bin/env python3
"""Generate the Soniqo iOS runner's Swift manifest from runtime inputs."""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

from scripts.external_bakeoff.schema import DEFAULT_OUTPUT_DIR, load_json, validate_manifest


DEFAULT_OUTPUT = (
    Path(__file__).resolve().parent
    / "SoniqoKokoroIOSRunner"
    / "Sources"
    / "BenchmarkManifest.generated.swift"
)


def _swift_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--manifest",
        type=Path,
        default=DEFAULT_OUTPUT_DIR / "runtime_input_manifest.json",
    )
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()

    manifest = load_json(args.manifest)
    validate_manifest(manifest)
    buckets = list(manifest["runtime_buckets"])
    inputs = manifest["inputs"]

    rows = []
    for key in buckets:
        item = inputs[key]
        rows.append(
            "    RuntimeInput(\n"
            f"        key: {_swift_string(key)},\n"
            f"        text: {_swift_string(item['text'])},\n"
            f"        textSHA256: {_swift_string(item['text_sha256'])},\n"
            f"        voice: {_swift_string(item['voice'])},\n"
            f"        canonicalDurationS: {float(item['canonical_duration_s']):.6f},\n"
            f"        expectedBucketS: {int(item['expected_bucket_s'])},\n"
            f"        speed: {float(item['speed']):.6f}\n"
            "    )"
        )

    content = (
        "// Generated by scripts/external_bakeoff/generate_ios_runner_manifest.py.\n"
        "// Do not edit by hand.\n\n"
        "import Foundation\n\n"
        "struct RuntimeInput: Identifiable, Sendable {\n"
        "    let id: String\n"
        "    let key: String\n"
        "    let text: String\n"
        "    let textSHA256: String\n"
        "    let voice: String\n"
        "    let canonicalDurationS: Double\n"
        "    let expectedBucketS: Int\n"
        "    let speed: Double\n\n"
        "    init(\n"
        "        key: String,\n"
        "        text: String,\n"
        "        textSHA256: String,\n"
        "        voice: String,\n"
        "        canonicalDurationS: Double,\n"
        "        expectedBucketS: Int,\n"
        "        speed: Double\n"
        "    ) {\n"
        "        self.id = key\n"
        "        self.key = key\n"
        "        self.text = text\n"
        "        self.textSHA256 = textSHA256\n"
        "        self.voice = voice\n"
        "        self.canonicalDurationS = canonicalDurationS\n"
        "        self.expectedBucketS = expectedBucketS\n"
        "        self.speed = speed\n"
        "    }\n"
        "}\n\n"
        "let runtimeInputs: [RuntimeInput] = [\n"
        + ",\n".join(rows)
        + "\n]\n"
    )

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(content)
    print(f"Wrote {args.output}")


if __name__ == "__main__":
    main()
